"""changed_rank_to _type_int

Revision ID: 0cf3c1c0f9fc
Revises: 77d428d83566
Create Date: 2023-05-29 13:17:10.708939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf3c1c0f9fc'
down_revision = '77d428d83566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.alter_column('rank',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.alter_column('rank',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
