"""Updated_type_2_column_as_nullable_true

Revision ID: 77d428d83566
Revises: 
Create Date: 2023-05-29 13:00:20.968321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d428d83566'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.alter_column('type_2',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.alter_column('type_2',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
